[package]
name = "bitcoin"
version = "0.1.1"
description = "Algorithms for bitcoin integration"
repository = "https://github.com/dfinity/motoko-bitcoin"
keywords = [ "bitcoin" ]
license = "Apache-2.0"

[dependencies]
core = "2.4.0"
sha2 = "0.1.14"

[dev-dependencies]
test = "2.1.2"
bench-helper = "0.0.3"

[toolchain]
wasmtime = "43.0.1"
moc = "1.5.0"
pocket-ic = "9.0.3"
