[package]
name = "bitcoin"
version = "0.2.1"
description = "Algorithms for bitcoin integration"
repository = "https://github.com/caffeinelabs/motoko-bitcoin"
keywords = [ "bitcoin" ]
license = "Apache-2.0"

[dependencies]
core = "2.6.0"
sha2 = "0.1.14"

[dev-dependencies]
test = "2.1.2"
bench-helper = "0.0.3"

[toolchain]
moc = "1.11.0"
pocket-ic = "14.0.0"
wasmtime = "44.0.3"

[requirements]
moc = "1.4.0"
