name: Tests and formatting

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review, unlabeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: ZenVoich/setup-mops@3e94e453352269b34137b5ce49f09a8df81bed7d # v1.4.1

      - name: make sure moc is installed
        run: mops toolchain bin moc || mops toolchain use moc latest

      - name: Show mops version
        run: mops -v

      - name: Install all mops dependencies
        run: mops install

      - name: run tests
        run: mops test

  format:
    name: Check formatting
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: "20"

      - name: Install prettier plugin
        run: npm install --save-dev prettier prettier-plugin-motoko

      - name: Run prettier check
        run: npx prettier --check --plugin=prettier-plugin-motoko **/*.mo
